<!--- Mohammad Idrees Bhat | Mohammad Idrees Bhat --->

<div style="background-color: #add8e6; padding: 10px; height: 70px; border-radius: 15px;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Ram<br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">Tech Skills Trainer | AI/ML Consultant</span>
    </div>
</div>

<h1 style=" background-color: #002147; color: White; padding: 30px; text-align:center"> Python Programming Language (Part 5) </h1>

<div style="background-color: lightgreen; color: black; padding: 10px;">
    <h1>Data Analysis with Python
</h1> </div>

<div style="background-color: grey; color: black; padding: 10px;">
    <h4><b>AGENDA</b> <p><p>
1. Introduction to Data Analysis and Python Libraries <p><p> 
2. NumPy Basics <p>
3. Introduction to Pandas <p>
4. Data Manipulation with Pandas <p>  
</h4> </div>

<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>1. Introduction to Data Analysis and Python Libraries 
</h4> </div>

## Overview of Data Analysis
Data analysis is the process of inspecting, cleansing, transforming, and modeling data to discover useful information, inform conclusions, and support decision-making. It is important because:

- **Informed Decision Making**: Data analysis helps organizations make informed decisions by providing actionable insights.
- **Identifying Trends and Patterns**: Analyzing data can uncover trends and patterns that can lead to new opportunities or help mitigate risks.
- **Performance Improvement**: By understanding data, organizations can optimize processes and improve overall performance.
- **Cost Reduction**: Effective data analysis can lead to cost savings by identifying inefficiencies.
- **Competitive Advantage**: Companies that leverage data effectively can gain a competitive edge in the market.


<div style="background-color: lightblue; color: black; padding: 4px;">
    <h4>Python Libraries
</h4> </div>

In Python, a library is a collection of modules and packages that provide pre-written code to perform common tasks. Libraries allow developers to reuse code, streamline their workflows, and leverage existing functionality without having to reinvent the wheel. This makes programming faster, easier, and more efficient.

### Why Use Python Libraries?

1. **Code Reusability**: Libraries contain reusable code, which means you can use existing functions and classes instead of writing your own from scratch. This saves time and reduces errors.

2. **Simplified Development**: Libraries offer pre-built solutions to complex problems, making it easier for developers to implement functionalities without delving into the underlying details.

3. **Community Support**: Popular libraries are often well-documented and maintained by a community of developers. This support makes it easier to learn and troubleshoot issues.

4. **Enhanced Functionality**: Libraries expand Python's capabilities, allowing you to perform a wide range of tasks, from data analysis to web development and machine learning.

5. **Focus on Higher-Level Concepts**: By using libraries, developers can focus on high-level application logic rather than low-level implementation details.

<div style="background-color: lightblue; color: black; padding: 4px;">
    <h4>Common Python Libraries
</h4> </div>

### 1. **NumPy**
- **Purpose**: Provides support for numerical computations and handling multi-dimensional arrays.
- **Applications**: Used in scientific computing, data analysis, and machine learning.

### 2. **Pandas**
- **Purpose**: Offers data structures like Series and DataFrame for data manipulation and analysis.
- **Applications**: Ideal for data cleaning, transformation, and exploratory data analysis.

### 3. **Matplotlib**
- **Purpose**: A plotting library for creating static, animated, and interactive visualizations in Python.
- **Applications**: Used for data visualization and creating informative graphs and charts.

### 4. **Scikit-learn**
- **Purpose**: A machine learning library that provides simple and efficient tools for data mining and data analysis.
- **Applications**: Used for building predictive models, classification, regression, and clustering.

### 5. **TensorFlow and PyTorch**
- **Purpose**: Libraries for building and training neural networks and deep learning models.
- **Applications**: Widely used in machine learning and artificial intelligence projects.

### 6. **Flask and Django**
- **Purpose**: Web development frameworks for building web applications in Python.
- **Applications**: Flask is lightweight for smaller applications, while Django is a robust framework for larger, more complex projects.

## How to Install Python Libraries

Python libraries can be easily installed using `pip`, the package installer for Python. For example, to install NumPy and Pandas, you can run the following command in your terminal:

```bash
pip install numpy pandas


<div style="background-color: lightblue; color: black; padding: 4px;">
    <h4> Introduction to NumPy and Pandas
</h4> </div>

### NumPy
- **Purpose**: NumPy (Numerical Python) is a library used for numerical computations. It provides support for arrays, matrices, and a variety of mathematical functions to operate on these data structures.
- **Applications**: It is widely used in scientific computing, data analysis, and machine learning due to its efficiency and ease of use.

### Pandas
- **Purpose**: Pandas is a library designed for data manipulation and analysis. It provides data structures such as Series and DataFrames, which are efficient for handling structured data.
- **Applications**: It is particularly useful for data cleaning, transformation, and analysis, making it a cornerstone for data analysis in Python.

## Installing and Setting Up the Libraries
To start using NumPy and Pandas, you need to install them. This can be easily done using pip, the package installer for Python. Here’s how to install them:

### Step 1: Open your command line or terminal.

### Step 2: Install NumPy and Pandas using pip:
```bash
pip install numpy pandas


In [1]:
# Importing the libraries
import numpy as np
import pandas as pd

# Check the versions to confirm installation
print("NumPy version:", np.__version__)  # Output the version of NumPy
print("Pandas version:", pd.__version__)  # Output the version of Pandas


NumPy version: 1.26.4
Pandas version: 2.2.2


<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>2. NumPy Basics
    </h4> </div>

NumPy is a powerful library for numerical computations in Python. It allows you to work with multi-dimensional arrays and provides functions to perform a variety of mathematical operations efficiently.

## 1. Why Use NumPy?

- **Efficiency**: NumPy arrays are faster and more memory-efficient than Python lists.
- **Mathematical Operations**: Supports complex mathematical operations with arrays, including element-wise operations.
- **Multi-Dimensional Arrays**: NumPy allows you to work with arrays of any dimension (1D, 2D, 3D, etc.).



## 2. Creating NumPy Arrays

The core feature of NumPy is the `ndarray` object. Let's start by creating an array:


In [11]:
import numpy as np

# Creating a simple 1D array
arr = np.array([1, 2, 3, 4, 5]) # creates a NumPy array.
print(arr) # [1 2 3 4 5]
type(arr)

[1 2 3 4 5]


numpy.ndarray

## 3. Performing Operations on Arrays

NumPy allows you to perform element-wise operations on arrays, making calculations easy and efficient.

### Key Points:
- **Element-wise operations** can be performed on arrays of the same shape.
- Operations can include **addition**, **subtraction**, **multiplication**, and **division**.


In [13]:
# Example: Adding two arrays

import numpy as np  # Importing the NumPy library

# Creating two arrays of the same shape
arr1 = np.array([1, 2, 3])  # First array
arr2 = np.array([4, 5, 6])  # Second array

# Performing element-wise addition
arr_sum = arr1 + arr2  # Adds corresponding elements in arr1 and arr2
print("Element-wise Addition:", arr_sum)  # Output: [5 7 9]

# Performing element-wise subtraction
arr_diff = arr1 - arr2  # Subtracts corresponding elements in arr2 from arr1
print("Element-wise Subtraction:", arr_diff)  # Output: [-3 -3 -3]

# Performing element-wise multiplication
arr_product = arr1 * arr2  # Multiplies corresponding elements in arr1 and arr2
print("Element-wise Multiplication:", arr_product)  # Output: [4 10 18]

# Performing element-wise division
arr_quotient = arr1 / arr2  # Divides corresponding elements in arr1 by arr2
print("Element-wise Division:", arr_quotient)  # Output: [0.25 0.4 0.5]


Element-wise Addition: [5 7 9]
Element-wise Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


## 3. Array Properties

NumPy arrays have properties that provide useful information about the array's structure, such as the number of dimensions and shape.

### Key Points:
- **Dimensions (ndim)**: The number of axes (or dimensions) of the array. For example, a 1D array has one dimension, while a 2D array has two.
- **Shape**: The size of each dimension of the array, returned as a tuple. For example, a 2D array with 3 rows and 4 columns will have a shape of `(3, 4)`.


In [15]:
print(arr.ndim)  # Output: 1, because it's a 1D array
print(arr.shape)  # Output: (5,), indicating the array has 5 elements in a single dimension


1
(5,)


## 4. Performing Operations on Arrays

NumPy allows you to perform element-wise operations on arrays, making calculations easy and efficient.

### Key Points:
- **Element-wise operations** can be performed on arrays of the same shape.
- Operations can include **addition**, **subtraction**, **multiplication**, and **division**.


In [37]:
# Accessing elements
print(arr[0])  # Output: 1 (first element)
print(arr[2])  # Output: 3 (third element)

# Slicing arrays
print(arr[1:4])  # Output: [2 3 4], elements from index 1 to 3 (index 4 is excluded).
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
#print(arr4[1:4])
print(arr4[1:])

1
3
[2 3 4]
[2 3 4 5 6 7 8 9 0]


In [35]:
print(arr4[1:])


[2 3 4 5 6 7 8 9 0]


In [49]:
#print(arr4[:])
#print(arr4[ : -2])
print(arr4[-4 : -1])
print(arr4[-4 : ])


[7 8 9]
[7 8 9 0]


<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>3. Introduction to Pandas
</h4> </div>

Pandas is a powerful and versatile open-source **data analysis and manipulation** library for Python. It is built on top of NumPy and provides high-performance, easy-to-use data structures and data analysis tools.

### Why Use Pandas?
Pandas is particularly useful for working with structured data (like tabular data) and provides the following key features:
- **Data Structures**: Includes Series and DataFrame, which allow you to easily store and manipulate data.
- **Performance**: Optimized for performance, making it suitable for handling large datasets efficiently.
- **Integration**: Works well with other libraries and tools in the data science ecosystem, such as Matplotlib for data visualization and Scikit-learn for machine learning.

Pandas is widely used in various fields, including finance, economics, statistics, and data science, to analyze and visualize data efficiently.


## Getting Started with Pandas

To use Pandas, you'll first need to install it. If you haven't installed Pandas yet, you can do so using pip:

```bash
pip install pandas


In [25]:
import pandas as pd  # Importing pandas with an alias for convenience

## Basic Data Structures in Pandas

Pandas primarily provides two data structures:

### 1. Series
- A Series is a one-dimensional labeled array that can hold any data type.
- It is similar to a list or an array but with labels (indices) associated with each value.
- It can be seen as a single column of a DataFrame.


In [55]:
import pandas as pd  # Importing pandas

# Creating a Series
data = [10, 20, 30, 40]  # Sample data for the Series
series = pd.Series(data)  # Creating a Series from the list
#series = pd.Series([10, 20, 30, 40]) # Can we write this ?
#series = pd.series(data) # Check if it works -> ?
print("Pandas Series:")
#print(series)  # Display the Series
series

Pandas Series:


0    10
1    20
2    30
3    40
dtype: int64

### 2. DataFrame
- A DataFrame is a two-dimensional labeled data structure with columns that can be of different types. It's similar to a table in a database or a spreadsheet.
- It can be thought of as a spreadsheet or SQL table, where you can organize data in rows and columns.

In [89]:
# Creating a DataFrame
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie'],  # Names of individuals
    'Age': [25, 30, 35],  # Corresponding ages
    'City': ['New York', 'Los Angeles', 'Chicago']  # Corresponding cities
}  
df = pd.DataFrame(data_dict)  # Creating a DataFrame from the dictionary
print("\nPandas DataFrame:")
#print(df)  # Display the DataFrame
df


Pandas DataFrame:


Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## Accessing Data in Pandas

Pandas provides easy ways to access and manipulate the data within Series and DataFrames.

### Accessing Series
You can access elements in a Series using their index.


### Accessing DataFrame
You can access columns, rows, and specific cells using various methods such as:
- **Accessing Columns**: Use `df['column_name']` to access a specific column in a DataFrame.
  - **Example**: `df['Column1']` retrieves the data in the 'Column1' column.
  
- **Accessing Rows by Index Position**: Use `df.iloc[]` to access rows by their integer index position. (Integer Location)
  - **Example**: `df.iloc[0]` retrieves the first row of the DataFrame.

- **Accessing Rows by Index Label**: Use `df.loc[]` to access rows by their index label. (Label Location)
  - **Example**: `df.loc[0]` retrieves the row with the index label '0'.

In [ ]:
# Accessing elements in a Series
print("First element in the Series:", series[0])  # Accessing the first element

# Accessing DataFrame columns
print("\nAccessing the 'Name' column:")
print(df['Name'])  # Display the 'Name' column

# Accessing DataFrame rows using iloc
print("\nAccessing the first row of the DataFrame using iloc:")
print(df.iloc[0])  # Display the first row

# Accessing DataFrame rows using loc (index label)
print("\nAccessing the row with index 1 using loc:")
print(df.loc[1])  # Display the row with index label 1


In [ ]:
# Example Usages
df.iloc[1:10] #retrieves the first 10 entries

In [115]:
import pandas as pd

# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}

df = pd.DataFrame(data, index = ['a','b','c']) # assigning custom row labels (index)
df
# Using .loc to select by label
print(df.loc['a'])          # Select row with index label 'a'
#print(df.loc['a':'b'])      # Select rows 'a' to 'b' (inclusive)
#print(df.loc['a', 'Name'])  # Select specific value (row 'a', column 'Name')


Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [119]:
import pandas as pd

# Sample DataFrame
data = {'Class': ['1', '2', '3'],
        'Age': [25, 30, 35]}

df = pd.DataFrame(data, index = ['amit','bachan','charlie']) # assigning custom row labels (index)
df

Class  Age
amit        1   25
bachan      2   30
charlie     3   35

In [ ]:


# Using .iloc to select by integer position
print(df.iloc[0])           # Select the first row
print(df.iloc[0:2])         # Select first two rows (index 0 and 1, exclusive of 2)
print(df.iloc[0, 0])        # Select the value at the first row and first column

In [107]:
# Using .iloc (Position-based)
df.iloc[0]        # Select first row

Name    Alice
Age        25
Name: a, dtype: object

In [121]:
# Using .loc (Label-based)
df.loc['amit']       # does not work with 0

Class     1
Age      25
Name: amit, dtype: object

<div style="background-color: lightgreen; color: black; padding: 4px;">
    <h4>4. Data Manipulation with Pandas 
</h4> </div>

## Data Manipulation with Pandas

Data manipulation is one of the primary functions of the Pandas library, allowing users to transform and analyze data efficiently. This section covers essential operations for data manipulation using Pandas DataFrames.

### Common Data Manipulation Operations

#### 1. Loading Data
Pandas allows you to load data from various sources, such as CSV files, Excel spreadsheets, and SQL databases.

In [135]:
# Example

import pandas as pd

# Load data from a CSV file
df = pd.read_csv('Iris.csv')  # Replace 'data.csv' with your file path
#df.head(10)
df.tail(15)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            NaN           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            NaN           2.3   
146  147            NaN           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
135  Iris-virginica  
136  Iris-virginica  
137  Iris-virginica  
138  Iris-virginica  
139  Iris-virginica  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

### 2. Inspecting Data

Inspecting data is a crucial step in understanding the structure and content of your DataFrame. Pandas provides several built-in methods that allow you to quickly view and summarize your data.

### Key Methods for Inspecting Data

1. **`.head(n)`**: This method is useful for getting a quick glance at your data. This helps you to quickly see a sample of the data and understand its structure.

2. **`.info(n)`**: This provides details about the DataFrame, including index type, columns, data types, and non-null counts.

In [139]:
#Replace 'df' with your DataFrame variable 

# Display the first 5 rows of the DataFrame
#print(df.head())  # Replace 'df' with your DataFrame variable
# Example: print(df.head(10))  # Displays the first 10 rows

# Display summary information about the DataFrame
# No parameters are required, but you can pass 'verbose=True' to display more information if the DataFrame is large.
#print(df.info())  # 
df.info()
# Example: print(df.info(verbose=True))  # Displays a detailed summary of the DataFrame


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  146 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


### 3. Selecting Data

Access specific rows and columns using `loc` and `iloc`.

In [ ]:
# Access a specific column
# This retrieves the data from the specified column in the DataFrame.
# Replace 'ColumnName' with the actual name of the column you want to access.
column_data = df['ColumnName']  # Accesses the column named 'ColumnName'

# Access rows by index position
# This retrieves the first row of the DataFrame using its index position (0-based).
first_row = df.iloc[0]  # Accesses the first row (index 0)

# Access rows by index label
# This retrieves the row using its index label.
# Ensure that the label exists in the DataFrame's index.
first_row_label = df.loc[0]  # Accesses the row with index label 0

In [155]:
#column_data = df['SepalLengthCm']  # Accesses the column named 'ColumnName'
#column_data
filtered_data = df[df['SepalLengthCm'] < 6]
filtered_data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
113  114            5.7           2.5            5.0           2.0   
114  115            5.8           2.8            5.1           2.4   
121  122            5.6           2.8            4.9           2.0   
142  143            5.8           2.7            5.1           1.9   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
113  Iris-virginica  
114  Iris-virginica  
121  Iris-virginica  
142  Iris-virginica  
149  Iris-virginica  

[82 rows x 6 columns]

### 4. Filtering Data

Filter data based on conditions to extract subsets of data.

In [151]:
# Filter rows where a specific column meets a condition
# This retrieves rows from the DataFrame where the values in 'ColumnName' are greater than 50.
# Replace 'ColumnName' with the actual name of the column you want to filter on,
# and adjust the condition as necessary (e.g., <, ==, !=, etc.).
filtered_data = df[df['ColumnName'] > 50]  # Filters rows based on the specified condition

KeyError: 'ColumnName'

### 5. Adding and Removing Columns

Filter data based on conditions to extract subsets of data.

In [ ]:
# Add a new column
# This creates a new column 'NewColumn' in the DataFrame by adding the values from 'Column1' and 'Column2'.
# Replace 'Column1' and 'Column2' with the actual column names you want to use for the addition.
df['NewColumn'] = df['Column1'] + df['Column2']  # Creates a new column based on the sum of two existing columns

# Remove a column
# This removes the specified column from the DataFrame.
# The 'axis=1' parameter indicates that a column is being dropped (use 'axis=0' for rows).
# The 'inplace=True' parameter modifies the DataFrame directly without returning a new object.
df.drop('ColumnName', axis=1, inplace=True)  # Removes the column named 'ColumnName'

In [157]:
df['SepalLengthCm'] = df['SepalWidthCm'] + df['SepalLengthCm']
df['SepalLengthCm'] 

0      8.6
1      7.9
2      7.9
3      7.7
4      8.6
      ... 
145    9.7
146    NaN
147    9.5
148    9.6
149    8.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [ ]:
# Rename columns
df.columns = ['Column1', 'Column2']
print(df)

In [ ]:
# Assigning custom index (row) names
df.index = ['Row1', 'Row2', 'Row3']
print(df)


### 6. Grouping Data

Group data by a specific column and perform aggregate functions.

In [ ]:
# Group by a column and calculate the mean
# This groups the DataFrame by the values in 'GroupColumn' and calculates the mean 
# for each group for all numeric columns.
# Replace 'GroupColumn' with the actual name of the column you want to group by.
grouped_data = df.groupby('GroupColumn').mean()  # Groups data by 'GroupColumn' and computes the mean

### 7. Sorting Data

Sort the DataFrame by one or more columns.

In [ ]:
# Sort the DataFrame by a specific column
# This sorts the DataFrame based on the values in 'ColumnName'.
# The 'ascending=True' parameter indicates that the sorting should be in ascending order.
# To sort in descending order, set 'ascending=False'.
# Replace 'ColumnName' with the actual name of the column you want to sort by.
sorted_df = df.sort_values(by='ColumnName', ascending=True)  # Sorts the DataFrame by 'ColumnName'


<div style="background-color: lightblue; color: white; padding: 10px; text-align: center;">
    <h1>_________________________________END________________________________
</h1> </div>

<div style="background-color: #002147; color: #fff; padding: 30px; text-align: center;">
    <h1>THANK YOU!
</h1> </div>